version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 --log-level=debug --access-logfile '-' --error-logfile '-' --capture-output --enable-stdio-inheritance manage:app
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev

  client:
    build: ./services/client
    ports:
      - 3000:3000
    env_file:
      - ./services/client/config/.env
#     depends_on:
#       - db
#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - ./.env.prod.db

# volumes:
#   postgres_data:
